### ISSUE TITLE
Дубль подкатегорий в Плодово-ягодных

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#1]
В категории Плодово-ягідні рослини дублируется подкатегория Дерева (с маленькой буквы внизу)
В русской версии такого нет.

Обнаружено на
HTC Desire 620G
5", 1280 x 720

**Comment by boberproduction** [comment]
Она дублируется потому, что в статье №2450 ("Яблуня") категория в тегах так и написана - "дерева", с маленькой буквы.
Допишу парсер, чтобы записывал все категории и семейства с большой буквы.

**Comment by sevbanchik** [comment]
Если проблема в этом, то проще мне исправить это дело в админке у себя.

**Comment by boberproduction** [comment]
Действительно проще.
