### ISSUE TITLE
Цвет фона и шрифта совпадает

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#10]
В выпадающем окне поиска с подсказками того, что ты недавно искал, пишет белым цветом на белом фоне.

![screenshot_2016-01-24-21-13-04](https://cloud.githubusercontent.com/assets/16124650/12538311/50621b4e-c2df-11e5-97a8-6076ca21a9bd.png)

Обнаружено на
HTC Desire 620G
5", 1280 x 720

**Comment by boberproduction** [comment]
Какая версия Android?

**Comment by sevbanchik** [comment]
4.4.2

**Comment by sevbanchik** [comment]
На версии 4.1.2 та же фигня (это на мелком телефоне).
И на планшете с андроидом 4.4.2.
