### ISSUE TITLE
Ошибка при повороте экрана

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#11]
Что делалось:
Захожу в Садовые растения, Деревья, Пихта. В поиске ввожу пихта. Поворачиваю экран с вертикального на горизонтальный – выдает ошибку (см. скрин ниже).
![screenshot_2016-01-24-21-14-38](https://cloud.githubusercontent.com/assets/16124650/12538333/fe6700b0-c2df-11e5-9029-4efe78659a8b.png)
Другой вариант:
Захожу в Садовые растения, Деревья, Пихта. В поиске ввожу пихта. Перехожу в результатах поиска на статью Пихта. Поворачиваю экран с вертикального на горизонтальный – выдает ошибку (см. скрин выше).

**Comment by boberproduction** [comment]
Исправлено в версии 0.3.2
