### ISSUE TITLE
Меню в верхнем левом углу

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#13]
Чтобы вернуться в главное меню из статьи, приходится листать несколько раз назад.
А если сделать меню, подобное тому, что у тебя в приложении ПРД 2015?

**Comment by boberproduction** [comment]
Могу сделать, но это может занять много времени.
Можно, скажем, в режиме статьи вместо стрелки "назад" показівать кнопку "Домой".

**Comment by sevbanchik** [comment]
Ну, давай эту менюху отложим до следующей версии программы (в смысле крупного обновления). Выпустим рабочую начальную, а потом будем добавлять всякие хорошие штучки.
