### ISSUE TITLE
Загружает маленькие фото

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#19]
На планшете
> Lenovo IdeaTab A5500
> 8", 1280 x 800

загружает маленькие фото.
В настройках выставлено "Определять автоматически". Раньше загружало большие фото. Для планшета с таким расширением и диагональю больше бы подошли крупные фотки.
Раньше было так (осталось в кэше, видать)
![screenshot_2016-01-31-20-51-58](https://cloud.githubusercontent.com/assets/16124650/12704145/98a23600-c85c-11e5-8c60-de3f952c3079.png)

Теперь стало так
![screenshot_2016-01-31-20-52-17](https://cloud.githubusercontent.com/assets/16124650/12704146/9ee3fe86-c85c-11e5-8f83-7aa3ba09471a.png)

**Comment by boberproduction** [comment]
Приложение сработало правильно: у твоего планшета плотность пикселей 189 точек на дюйм, а полноразмерные фотки грузятся для топовых девайсов с > 360 dpi.
Задумка в том, что на устройствах с невысокими разрешениями физическая ширина фотографий с шириной 300px (= 300dp) будет около 5см, то есть достаточно для того, чтобы её рассмотреть и не тратить лишний трафик. Причем абсолютные размеры картинки одинаковые что на телефоне, что на планшете, но на широком экране планшета выглядят хреново из-за пустого места по бокам.
При dpi > 360, те же фотки на экране такого же размера будут либо вдвое меньше, либо растянуты с потерей качества, поэтому там грузим полный размер.

В общем, как скажешь, могу сделать, чтобы качало полный размер при ширине экрана > n вне зависимости от разрешения. При этом можно добавить галочку "полноразмерные фото загружать только с wifi".

**Comment by boberproduction** [comment]
> В общем, как скажешь, могу сделать, чтобы качало полный размер при ширине экрана > n вне зависимости от разрешения. При этом можно добавить галочку "полноразмерные фото загружать только с wifi".

Наверное, так будет в самый раз.

**Comment by sevbanchik** [comment]
Давай оставлять пока, как есть. Цель — снижение нагрузки на сервак, поэтому грузить большие без нужды не будем.
