### ISSUE TITLE
Кнопка "назад" перепрыгивает страницу

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#2]
Идем в поиск, ищем статью, например, Морковь, открываем. Ищем в статье ссылку на другую статью, например, Капуста, переходим. Нажимаем на кнопку назад и попадаем опять в поиск, А не на статью о Моркови.
В украинской версии аналогично.

Обнаружено на
HTC Desire 620G
5", 1280 x 720

**Comment by boberproduction** [comment]
Исправлено в версии 0.3.2
