### ISSUE TITLE
Не понятно, как выбирает размер фото для загрузки

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#20]
На телефоне загружает то фото большого размера, то маленького. Не понятна логика, как он выбирает. То на вертикальном положении грузит большие картинки, то мелкие.

**Comment by boberproduction** [comment]
Упорно клацал в разных режимах, всё правильно грузит.
А что у тебя в настройках?

**Comment by sevbanchik** [comment]
Закрывай тему. Эту и другую с картинками.
