### ISSUE TITLE
Межстраничный баннер

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#23]
Баннер отображается, как и положено, только при переходе между статьями, но при переходе от каждой статьи. В настройках баннера стоит отображение 1 раз в течение 2 минут.
Вот и вопрос, в чем может быть проблема? 
Или это так пробный баннер работает, чтобы видеть как он работает, либо это бок у adblock'а, либо что еще.
Может у тебя соображения какие есть?

**Comment by boberproduction** [comment]
Это демо-баннер, на него твои настройки не действуют.
