### ISSUE TITLE
Ошибка при "загрузить фото"

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#25]
В статье о Клематисах выдает ошибку, если нажать на "Загрузить фото" в верхней части статьи.

**Comment by boberproduction** [comment]
Ошибка в названии файла на сервере - http://floristics.info/images/stati_photo/clematis/clematis25_raskidistyy_joan_pikton.jpg.
В слове "joan" стоит кириллическая "а", и для приложения это выглядит так: http://floristics.info/images/stati_photo/clematis/clematis25_raskidistyy_jo%D0%B0n_pikton.jpg.
Та же фигня и в папке images_300.

До конца недели я, как можно догадаться, не успел, нужно ещё несколько дней, чтоб довести всё до ума.

**Comment by sevbanchik** [comment]
Спасибо, я поправлю файлы на серваке.

Как будет, так и будет. Я ж что? Я ж ниче.

**Comment by sevbanchik** [comment]
Дело в том, что ошибка не только с той фоткой, где русская А, но и с другими картинками в этой статье.
