### ISSUE TITLE
Вылетает приложение

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#27]
Если добавить несколько заметок в блокнот из одного материала (может и из разных), потом зайти в блокнот, удалить одну из записей, нажав на крестик, а потом нажать на другую, чтобы отредактировать, то приложение подвисает и вылетает.

**Comment by sevbanchik** [comment]
То же происходит и если удалить заметку, написанную самостоятельно, и сразу открыть следующую.

**Comment by sevbanchik** [comment]
Если удалить заметку, немного подождать, а потом открыть следующую, то ошибку может не выдать, а может и выдать.

**Comment by boberproduction** [comment]
Может исправил, а может и нет.

**Comment by sevbanchik** [comment]
Похоже, что исправил. Пока ставим фикс, если что – воскресим.
