### ISSUE TITLE
Есть ссылка на аудио в содержании

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#3]
В некоторых украинских статьях присутствует ссылка на Аудио. Есть такое точно в Жоржина и Гладіолус, Гузманія, Іпомея.
Заметил и в Диффенбахія.

![screenshot_2016-01-24-00-23-31](https://cloud.githubusercontent.com/assets/16124650/12533241/3ed67440-c232-11e5-86ff-52065a374c1d.png)

Обнаружено на
HTC Desire 620G
5", 1280 x 720

**Comment by boberproduction** [comment]
Исправлено в версии 0.3.2
