### ISSUE TITLE
Замия - не грузятся фото

### ISSUE THREAD

**Issue by boberproduction** [boberproduction/FloristX#31]

**Comment by sevbanchik** [comment]
В замии нет фото, кроме основного. Грузиться нечему.

**Comment by boberproduction** [comment]
А кнопки есть.

**Comment by sevbanchik** [comment]
А заскринь, плз. У меня в замии нет никаких кнопок.

**Comment by boberproduction** [comment]
Это у меня старая версия приложения. Отбой.

**Comment by sevbanchik** [comment]
Сбросить тебе новую? =)

**Comment by boberproduction** [comment]
:) Я на работе

**Comment by sevbanchik** [comment]
Так себе отмазка.
