### ISSUE TITLE
Слишком много работаешь.

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#32]
Ты слишком много работаешь, поэтому не можешь в полной мере посвятить себя разработке приложений – своих и вообще. С этим нужно что-то делать.
Напиши, когда пофиксишь этот баг.

**Comment by boberproduction** [comment]
На это я пойти не могу! Мне нужно посоветоваться с шефом.

**Comment by sevbanchik** [comment]
Вижу, что ты фиксишь этот баг. =)

**Comment by boberproduction** [comment]
Вроде бы пофиксил.
