### ISSUE TITLE
Не создает иконку на десктопе

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#33]
Так только наше приложение у меня в телефоне не создает иконку на десктопе после установки. Все остальные приложения при установке создают иконку не только в программе, но и на рабочем столе.
Так большэ жыть низзя (с)

**Comment by boberproduction** [comment]
Что происходит, если установить его с маркета, а не апк?
Размещением иконок при установке занимается Google Play, у него в настройках можно вкл/выкл эту опцию. Само приложение, насколько мне известно, на это повлиять не может.

**Comment by sevbanchik** [comment]
Вроде бы уже создает иконку. При установке из Маркета.
