### ISSUE TITLE
FB-иконка не предлагает открыть в приложении

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#34]
Иконки TY и VK предлагают открыться помимо браузеров в установленных приложениях. А FB не предлагает. Это баг у меня, или нормальное положение вещей?

**Comment by boberproduction** [comment]
Баг фейсбукового приложения, https://developers.facebook.com/bugs/332619626816423
Посмотрю, что можно сделать.

**Comment by sevbanchik** [comment]
Если баг не наш, то оно само исправится, когда его исправят фейсбучники. Нечего и голову забивать.
