### ISSUE TITLE
В приложении "Флорист-X" произошла ошибка

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#35]
Нет возможности проверить многие функции, поскольку после захода в подкатегорию одной из категорий, выдаёт ошибку (см. сабж). То же происходит, если зайти в меню Семейства растений. В общем, ни одну статью открыть не удалось.
**Добавлено**
Удалось определить, что эта ошибка возникает, если в настройках стоит галочка на "Отображение фото растений в ...". Если галочку убрать, то статьи открываются.

**Comment by boberproduction** [comment]
Позорище.
Где мой пепел для посыпания головы?

**Comment by sevbanchik** [comment]
Вроде бы не происходит ошибка уже.
