### ISSUE TITLE
Не отображать class="display-none-android"

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#4]
Я добавлю некоторым блокам класс display-none-desktop. Эти блоки показывать в приложении не нужно. А то получается вот такая вот фигня, как в Астрах, например.

![screenshot_2016-01-24-00-38-57](https://cloud.githubusercontent.com/assets/16124650/12533283/9c453b56-c233-11e5-998b-45c204ace86f.png)

**Comment by boberproduction** [comment]
Исправлено в версии 0.3.2

**Comment by sevbanchik** [comment]
А также не отображать блоки с классом
none-in-cat

**Comment by boberproduction** [comment]
Сделаем.
Новую версию сброшу завтра утром. 
И завтра же отбываю в Карпаты со сменой на 3 дня, буду недееспособен.

**Comment by sevbanchik** [comment]
Или класс none-in-cat не добавлен, или что-то пошло не так. В "Ипомея" блок с этим классом отображается (в обеих версиях)

**Comment by boberproduction** [comment]
Ага, none-in-cat забыл добавить, исправил.
Так всё-таки прятать display-none-android или display-none-desktop? Или оба?

**Comment by sevbanchik** [comment]
Прятать display-none-android, display-none-desktop, none-in-cat
