### ISSUE TITLE
Нельзя добавить свою задачу

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#46]
Сабж. Нет пункта Другое. По крайней мере на экране. И, следовательно, нельзя создать сад задачу, которой нет в списке. 
На скрин пролистал до низа.
![screenshot_20170725-132959](https://user-images.githubusercontent.com/16124650/28568220-a5ff749e-713d-11e7-9d6d-4aa8c3879206.png)

**Comment by boberproduction** [comment]
А я ж написал в релизе, что это единственное, что пока не доделано.

**Comment by sevbanchik** [comment]
У тебя написано, что не работает выбор одновременно нескольких задач. Я о другом пишу. Нет возможности самому написать задание, а не выбрать из списка.
