### ISSUE TITLE
Изменения в главном меню

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#47]
Предлагаю для уменьшения нагромождения и улучшения внешнего вида немного изменить главное меню. 
Переименовать "Все растения" в "Растения", сделать кнопку "Болезни и вредители" (я пришлю), оставить "Календарь садовода" и "Менеджер растений", оставить "Блокнот" и "Избранное".
Аудио оставить только в боковом меню, как ты сделал с "Семейства". В Укр аудио не будет, как и нет его сейчас.
При нажатии на "Все растения" пусть появляется всплывающее окно (как при нажатии на "Размер фотографий" в настройках изображений), где и можно будет выбрать уже "Комнатные растения", "Садовые ..." и т.д. На скрине ниже я схематически изобразил. При нажатии на новый пункт "Болезни и вредители" будет появляться всплывающее окно, где будет две кнопки – Болезни растений и "Вредители растений" по аналогии с тем, что я писал чуть выше. Какие твои мысли по поводу таких изменений?
![default](https://user-images.githubusercontent.com/16124650/28572283-fd865316-714e-11e7-84cc-05846aaeadc3.jpg)

**Comment by boberproduction** [comment]
Вот нашёл статистику по модулям из старой аналитики (она, кстати, до сих
пор активно используется юзерами со старыми версиями приложения)
https://analytics.google.com/analytics/web/#report/app-content-pages/a64636278w111243246p116062651/%3F_u.date00%3D20170101%26_u.date01%3D20170724%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowCount%3D10%26explorer-table.rowStart%3D0%26explorer-graphOptions.selected%3Danalytics.nthMonth/

Так вот там кнопки "Садовые растения", "Комнатные", "Семейства" и т.д.
используются чаще, чем "Избранное" и "Блокнот"

По поводу обьединения болезней и вредителей - согласен.

2017-07-25 15:34 GMT+03:00 sevbanchik <notifications@github.com>:

**Comment by sevbanchik** [comment]
Вот так я предлагаю сделать главное меню.

![obrazes](https://user-images.githubusercontent.com/16124650/28709510-461a2a6c-7389-11e7-99db-6d3c349d0dbd.jpg)

Если есть возможность нехлопотно сделать так, чтобы было такое меню, а в настройках можно было включить отображение всех пунктов на главной странице – было бы круто. Т.е. в новой версии по умолчанию будет сокращенное меню, а в настройках можно переключать между сокращенным и полным.

**Comment by sevbanchik** [comment]
Выглядит замечательно!
