### ISSUE TITLE
Размеры загружаемых фото

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#5]
На телефоне разрешение экрана 1280 x 720, фотки загружены в папку
Телефонна пам'ять\Android\data\ua.boberproduction.floristx\files\images\stati_photo\blueberry
Но сами фотографии маленького размера, как для маленького экрана.
Так должно быть?

Обнаружено на
HTC Desire 620G
5", 1280 x 720

На планшете загрузились крупные фотки

**Comment by boberproduction** [comment]
Да, так должно быть. Все фотки грузятся в папку ...files\images.

**Comment by sevbanchik** [comment]
А как программа решает, какие фотки загружать? В зависимости от диагонали?

**Comment by boberproduction** [comment]
В зависимости от dpi - плотности пикселей или кол-ва пикселей на дюйм длины.
Здесь подробнее об этом: http://puregoogle.ru/2013/07/26/nemnogo-o-dpi-i-podderzhke-xxxhdpi-v-android
Приложение качает полноразмерные фотки для экранов с dpi >= 360.

**Comment by sevbanchik** [comment]
Понял. Это, пожалуй, круто.
