### ISSUE TITLE
Выделение текущего дня в календаре

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#50]
Что-то случилось. Раньше было красиво, а теперь немного странно...
![screenshot_2017-07-28-09-39-33](https://user-images.githubusercontent.com/16124650/28705987-dc38a640-737a-11e7-9330-5e6e396d738a.png)

![screenshot 28 2017 9_56_47](https://user-images.githubusercontent.com/16124650/28706113-860e65a6-737b-11e7-8020-6c3fa5d45dde.jpg)

**Comment by sevbanchik** [comment]
Опять красивенько. А как масштабируются цифры в календаре? На планшете 8'' как-то мелко смотрятся цифры в календаре. На телефоне прекрасно.

**Comment by sevbanchik** [comment]
От не слава богу с этим календарём...
В книжной ориентации норм, в альбомной беда...
Планшет
![screenshot_2017-08-06-12-46-54](https://user-images.githubusercontent.com/16124650/29002208-f567135e-7aa5-11e7-9f54-3215484a71f7.png)
Телефон
![screenshot 6 2017 12_52_01](https://user-images.githubusercontent.com/16124650/29002215-2205dd50-7aa6-11e7-94df-75f44fa5020f.jpg)

**Comment by boberproduction** [comment]
А как должно быть?

**Comment by sevbanchik** [comment]
Я думал, что один месяц умещается в один экран по ширине и высоте.

**Comment by boberproduction** [comment]
Сделал поменьше. Но всё равно не факт, что будет помещаться полностью, маловато места по высоте, особенно с включенной рекламой.

**Comment by sevbanchik** [comment]
Восхитительный календарь!
