### ISSUE TITLE
Кнопка напоминания в статье

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#54]
Неплохо бы, чтобы в статье внизу справа (не перекрывая рекламу), находилась кнопка, как в приложении gmail, например, создать новое письмо.

![screenshot 31 2017 11_54_46](https://user-images.githubusercontent.com/16124650/28770336-6dc329dc-75e7-11e7-87b7-52657806b3b0.jpg)

Только создавать оно будет новое напоминание: открывать страницу с созданием напоминания, где в "Названии растения" будет уже стоять название растения, на странице которого юзер нажал на эту кнопку. Кнопку я сделаю и вышлю на почту.

**Comment by boberproduction** [comment]
Гугл говорит, что такая кнопка (Floating Action Button) должна вести к действию, основному для данного приложения/экрана.
Т.е. для почтового приложения - написать письмо. Для звонилки - набрать номер, и т.д.
По-моему, нерационально будет постоянно закрывать кусок контента кнопкой, пользоваться которой будет очень малая доля юзеров.

https://habrahabr.ru/post/231429/
https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

**Comment by boberproduction** [comment]
А такую функцию можно было бы влепить в существующее меню, там где "Открыть статью на сайте", "Добавить в избранное", и т.д.

**Comment by sevbanchik** [comment]
Ну давай так. Это вариант.

**Comment by sevbanchik** [comment]
Работает! Превосходно!
