### ISSUE TITLE
Дубли напоминаний

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#56]
Со второй недели напоминания, выставленные, на каждый день, начали дублироваться в пушах.

![screenshot_20170801-195439](https://user-images.githubusercontent.com/16124650/28837037-ff9de1be-76f3-11e7-83cf-c1b939fc72e2.png)

**Comment by sevbanchik** [comment]
Ошибся. Это выставлено напоминание " каждый вторник"

**Comment by boberproduction** [comment]
А в списке напоминаний оно одно?

**Comment by sevbanchik** [comment]
Так точно.

**Comment by sevbanchik** [comment]
Ждать целую неделю – долго. Я прокрутил часы на телефоне до этой даты, за две минуты до нужного времени. Вроде бы нет дублей. Прокрутил ещё на неделю вперёд - тоже одно сообщение. Будем слушать гневные отзывы наших любимых пользователей.
