### ISSUE TITLE
Главная страница не компактная

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#57]
После обновления главная страница остается некомпактной. Если зайти в настройки, то развернутое главное меню не включено, т.е. как бы должно отображаться свернутое. Если включить галочку - ничего не изменится, но если потом её убрать, то меню таки становится свернутым... Обновление проходило при запущенной программе.

**Comment by sevbanchik** [comment]
Не знаю, как это проверять теперь. Будем надеяться, что она будет компактной.

**Comment by boberproduction** [comment]
Я только что обновил приложение из маркета, меню становится компактным.

**Comment by sevbanchik** [comment]
Если так, тогда закрываем.
