### ISSUE TITLE
Не подгружает фотку(и)

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#6]
Неоднократно было, хотя вроде бы не каждый раз срабатывает.
При цепочке "Поиск – Статья – Другая статья по ссылке – Загрузить одиночную картинку" не загружает картинку (не выводит на экран).
В пример: Главная страница – Поиск – Клубника – Бархатцы
Если после этого нажать назад – выбросит в  поиск (если ты не поправил этот баг – https://github.com/boberproduction/FloristX/issues/2). Если после этого опять повторить цепочку Клубника – Бархатцы, то картинка, которую мы пытались подгрузить, окажется на том месте, где и должна быть. Мне это кажется странным.

Обнаружено на
HTC Desire 620G
5", 1280 x 720

Дополняю.
Если после проделанных выше действий нажать на кнопку "Загрузить все фото", то они начнут грузиться (появится гифка загрузки), и не загрузятся (не отобразятся). Если нажать "Назад", потом опять на Клубнику, потом опять на бархатцы, то окажется, что все картинки загружены и отображаются.
Мне это кажется странным 2.

**Comment by boberproduction** [comment]
Не получается воспроизвести, вроде всё подгружается как нужно. 
Возможно, этот баг был связан с одним из предыдущих, уже исправленных багов.

**Comment by sevbanchik** [comment]
Да, проверил несколько вариантов, все работает. Считаем, что фикст
