### ISSUE TITLE
Вот такое вот написало...

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#61]
![screenshot 3 2017 13_24_10](https://user-images.githubusercontent.com/16124650/28917695-2cb3e5de-784f-11e7-8d1f-98fe5cb757bc.jpg)

**Comment by boberproduction** [comment]
А вот это обидно вообще

**Comment by boberproduction** [comment]
Оно такое пишет из-за большого количества ошибок при тестинге. Оно не знает, что версия ещё не рабочая.

**Comment by sevbanchik** [comment]
Успокаивай себя, конечно. :-)

**Comment by sevbanchik** [comment]
Раз это временное явление – закрываем.
