### ISSUE TITLE
Шрифт в поиске

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#63]
Теперь в поиске странный шрифт =)
![screenshot 6 2017 12_28_24](https://user-images.githubusercontent.com/16124650/29002075-e8a5de0a-7aa2-11e7-9ccd-c156963204c3.jpg)

**Comment by boberproduction** [comment]
Жуть какая!

2017-08-06 12:29 GMT+03:00 sevbanchik <notifications@github.com>:

**Comment by sevbanchik** [comment]
Замечательный шрифт. Всегда о таком мечтал!
