### ISSUE TITLE
Верхняя панель в статьях

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#64]
Предлагаю незначительно изменить верхнюю панель.  Сейчас мы имеем что:
![screenshot 6 2017 13_01_45](https://user-images.githubusercontent.com/16124650/29002288-9f0dfe6c-7aa7-11e7-8012-0be08c77d329.jpg)

Т.е. Название приложения с красивым шрифтом, название статьи, кнопку поиска и кнопку загрузки всех картинок. Далее выпадающий список с прочими возможностями. Если ориентация экрана альбомная при загрузке приложения, то туда еще добавляется кнопка добавления в избранное.

Я предлагаю на страницах статей (не в меню, не в категории, не в списке подкатегории, а именно уже на странице статьи) не писать красиво Флорист-Х (вообще никак не писать), не писать название открытой статьи, потому что оно дублируется в теле статьи (ты об этом когда-то что-то говорил), но сделать так, чтобы в верхней панели сразу помещались кнопки поиска, загрузки всех картинок, добавления в избранное и добавления напоминания. Остальное оставить в выпадающем списке.

Проделать такие манипуляции со статьями в разделах о растениях, в болезнях и вредителях и календаре садовода.

**Comment by boberproduction** [comment]
А в аудио?

**Comment by sevbanchik** [comment]
Хороший вопрос, а то я уж и забыл об этом разделе. Можно и в аудио так, как в разделах со статьями.

**Comment by sevbanchik** [comment]
Великолепная верхняя панель! Лучше и представить себе не мог.
