### ISSUE TITLE
Шрифт меню и маленький экран

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#7]
На телефоне с мелким экраном нечётко виден шрифт в главном меню. См. скрины

Обнаружено на
Samsung GALAXY Star GT-S5282
3", 320 x 240

![screenshot_2013-01-20-03-48-19](https://cloud.githubusercontent.com/assets/16124650/12533423/1ab89164-c238-11e5-891e-611cb43a220e.png)
![screenshot_2013-01-20-03-48-41](https://cloud.githubusercontent.com/assets/16124650/12533422/1a6e5464-c238-11e5-8914-2e1a544a04bc.png)

**Comment by boberproduction** [comment]
Эксперимент показал, что этот шрифт так ведёт себя на экранах с низким разрешением, и изменение размера шрифта ничего к лучшему не изменяет. Быть жирным он не умеет.

Предлагаю 2 варианта решения:
1. На экранах с низким разрешением (а таких сейчас 2,9% среди андроид-девайсов) использовать системный шрифт(см.скриншот)
![device-2016-01-24-190946](https://cloud.githubusercontent.com/assets/13077794/12537724/e0578a7e-c2ce-11e5-8be6-4ec5a22576c1.png)

2. Изменить шрифт главного меню для всех экранов на более гибкий.

**Comment by sevbanchik** [comment]
Давай
>> На экранах с низким разрешением (а таких сейчас 2,9% среди андроид-девайсов) использовать системный шрифт

**Comment by boberproduction** [comment]
Исправлено в версии 0.3.2
