### ISSUE TITLE
Название статьи крупно

### ISSUE THREAD

**Issue by sevbanchik** [boberproduction/FloristX#8]
Поскольку не всегда и не на всех экранах выводится название статьи полностью (может обрезаться), можно ли его выводить над картинкой?
Стиль такой же, как на сайте –http://floristics.info/ru/stati/2540-nefrolepis-v-domashnikh-usloviyakh.html

**Comment by boberproduction** [comment]
Можно, конечно. Но на моём телефоне даже "Пион древовидный" помещается без сокращений, а не вмещаются разве что совсем длинные заголовки вроде "Виноград  (уход осенью)".

**Comment by boberproduction** [comment]
Исправлено в версии 0.3.2
